(part "TNPW06031K00BEEA"
    (packageRef "RESC1608X55N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "71-TNPW06031K00BEEA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Dale/TNPW06031K00BEEA?qs=U8jWr0D8IJhJummGFaCE2g%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "TNPW06031K00BEEA")
    (property "Description" "Vishay 1k, 0603 (1608M) Thin Film SMD Resistor +/-0.1% 0.1W - TNPW06031K00BEEA")
    (property "Datasheet_Link" "")
    (property "symbolName1" "TNPW06031K00BEEA")
)
