(part "MMDT3904-7-F"
    (packageRef "SOT65P210X110-6N")
    (interface
        (port "1" (symbPinId 1) (portName "E2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "B2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "C1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "E1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "B1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "C2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "621-MMDT3904-F")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/MMDT3904-7-F?qs=57mY3cMFOgk2hRxwFAQcAA%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "MMDT3904-7-F")
    (property "Description" "Diodes Inc MMDT3904-7-F Dual NPN Bipolar Transistor, 200 mA, 40 V, 6-Pin SOT-363")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/ds30088.pdf")
    (property "symbolName1" "MMDT3904-7-F")
)
