(part "3296W-1-103LF"
    (packageRef "3296W1503LF")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-3296W-1-103LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/3296W-1-103LF?qs=CL3xLxiry19Id6AEaxYcng%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "3296W-1-103LF")
    (property "Description" "Trimmer Resistors - Through Hole 3/8" 10Kohms Sealed Vertical Adjust")
    (property "Datasheet_Link" "https://www.bourns.com/pdfs/3296.pdf")
    (property "symbolName1" "3296W-1-103LF")
)
