(part "RD901F-40-15F-A100K-00DL1"
    (packageRef "RD901F4015FA100K00DL1")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MH_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "MH_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "311-1940F-15F-A100K")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Alpha-Taiwan/RD901F-40-15F-A100K-00DL1?qs=1mbolxNpo8df9DDnn792hQ%3D%3D")
    (property "Manufacturer_Name" "Alpha (Taiwan)")
    (property "Manufacturer_Part_Number" "RD901F-40-15F-A100K-00DL1")
    (property "Description" "Potentiometers 9mm Audio 100K Flat Shaft,100M at 250V DC,300V AC 50V AC")
    (property "Datasheet_Link" "http://www.taiwanalpha.com.tw/downloads?target=products&id=113")
    (property "symbolName1" "RD901F-40-15F-A100K-00DL1")
)
