(part "UES1H100MPM1TD"
    (packageRef "CAPPRD350W60D825H1300")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "647-UES1H100MPM1TD")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nichicon/UES1H100MPM1TD?qs=WJSLByB5Mu08yl%252B5YJ7rqQ%3D%3D")
    (property "Manufacturer_Name" "Nichicon")
    (property "Manufacturer_Part_Number" "UES1H100MPM1TD")
    (property "Description" "Aluminum Electrolytic Capacitors - Radial Leaded 10uF 50 Volts 20%")
    (property "Datasheet_Link" "https://www.nichicon.co.jp/english/series_items/catalog_pdf/e-ues.pdf")
    (property "symbolName1" "UES1H100MPM1TD")
)
